### ISSUE TITLE
Tests raise "The TimeGate returned with HTTP status 429 and did not redirect to a Memento."

### ISSUE THREAD

**Issue by refeed** [mementoweb/py-memento-client#19]
Some `memento_client` tests on Travis and my computer raise `MementoClientException` with message "The TimeGate (...) returned with HTTP status 429 and did not redirect to a Memento."

The full log in travis: https://travis-ci.org/refeed/py-memento-client/jobs/253494646

Below was taken from https://travis-ci.org/refeed/py-memento-client/jobs/253494646#L3948 :
```
E           memento_client.memento_client.MementoClientException: The TimeGate (http://timetravel.mementoweb.org/timegate/http://www.webcitation.org/5QOywUODl) returned with HTTP status 429 and did not                 redirect to a Memento.
```

This is probably caused by the timegate server (http://timetravel.mementoweb.org) blocks the connection from the client, because the test is using `pytest-xdist` which runs the test with parallelization, and that sends many requests to the timegate server concurrently.

**Comment by hariharshankar** [comment]
b133b44 & release v0.6.0 fixes this issue.
