### ISSUE TITLE
Unclosed socket ResourceWarning on Python 3

### ISSUE THREAD

**Issue by jayvdb** [mementoweb/py-memento-client#6]
memento client isnt closing a socket, causing a ResourceWarning on Python 3, which is not ignored unless Python was built without debug enabled.

```
WARNING: /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/memento_client/memento_client.py:132: ResourceWarning: unclosed <ssl.SSLSocket fd=25, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.8.19', 58618), raddr=('172.217.2.196', 443)>
  original_uri = self.get_original_uri(request_uri)
```

from https://travis-ci.org/wikimedia/pywikibot-core/jobs/115483178#L3757

**Comment by shawnmjones** [comment]
Thanks for the heads up.  I'm looking into it.

**Comment by shawnmjones** [comment]
Our research shows that this is the behavior of the `urllib3` library under Python 3. The following link leads to a specific location in the conversation on this issue:
https://github.com/kennethreitz/requests/issues/1882#issuecomment-33297709

One developer who works on both `urllib3` and `requests` states they are not even confident that this is a bug (link below leads to part of conversation) and may even have been a deliberate design decision:
https://github.com/kennethreitz/requests/issues/1882#issuecomment-52281285

We use the requests library in our code, which uses `urllib3`.  It looks like `requests` leaves the socket open for performance reasons, using pooling to manage the sockets and closing them at some point in the future.

The documentation for `requests` states that the connection is released back to the pool once all of the data is consumed.  Seeing as we are making `HEAD` requests and then reviewing all of the headers, we do consume the data.

On lines 49-53 of `requests/api.py`, they use a `with` statement to close the connection when no longer in use:
https://github.com/kennethreitz/requests/blob/master/requests/api.py#L49

They even suggest a workaround to ignore the warning (link below leads to part of conversation):
https://github.com/kennethreitz/requests/issues/1882#issuecomment-42268849

**Comment by jayvdb** [comment]
Suppressing the warning will not work.  However, calling `Session.close` should work, but that means `MementoClient` needs session handling.  The simplest way to implement session handling is for `MementoClient` to become a context handler, and then `MementoClient.__exit__()` can call `Session.close()`.  An explicit `MementoClient.close()` could also close the Session for situations where the MementoClient can't be used in a context block.

**Comment by shawnmjones** [comment]
I appreciate the suggestions for the context handler using the `requests` `Session` object.  We are a bit reluctant to make this change, especially considering we chose the `requests` library because it performs its own connection pooling to begin with.

Are you sure there is not an alternative course of action for Pywikibot?  Especially considering that this is a known issue with `requests`, as referenced above, that only occurs because of `urllib3`?

**Comment by jayvdb** [comment]
A requests Session object also provides its own connection pooling.

The only negative of using a `Session` is that connections made within the memento_client will not be pooled with connections made using requests outside of the memento_client.

I believe it is quite unlikely the code calling memento_client will also be accessing the timegate/timemap servers directly -- the calling code should use memento_client for any requests to the timegate/timemap servers.

However the calling code might wish to use connections to the original uri's, so there will be some opportunity to re-use those connections.

A way to allow good results in all cases is that the `MementoClient` constructor could take an optional `session` parameter, so that the calling code can allow `MementoClient` to share its existing session, which it will close at an appropriate time.  If the caller doesnt provide a session, `MementoClient` would create its own.

> Are you sure there is not an alternative course of action for Pywikibot?

We would need to dig into the internals of `requests`.  e.g. we might manually close the connections which are no longer needed and should be pro-actively closed.  We like connection pooling of the requests to the timegate, however the resources consumed by keeping connections to the original urls need to be released as weblinkchecker.py spawns many threads with many connections and thus needs unneeded connections to be closed.

There may be some `requests` flags that we can set that helps weblinkchecker to pin the timegate connection open but pro-actively close other connections.  I'll look into this.

**Comment by shawnmjones** [comment]
I wanted to touch base and see how things were going on your end.

I have created the optional session argument you requested.  The code is in review locally.

Did you find anything else was needed for requests?

**Comment by jayvdb** [comment]
IMO `is_timegate` and `is_memento` should be the same type of method; either a normal instance method or a `staticmethod` .

**Comment by shawnmjones** [comment]
Agreed.  Through the course of testing/debugging with the session variable `@staticmethod` was removed, and will be added back on the next commit.  Thanks for catching this.

**Comment by shawnmjones** [comment]
After speaking with @hariharshankar today, we found some other areas that could be optimized while still retaining the same interface for existing users.  I have not submitted the pull request from my repository yet.

Was anything else needed, related to the `requests` library?

**Comment by jayvdb** [comment]
Sorry I havent replied more quickly.
We do have another ticket open that is roughly related
https://phabricator.wikimedia.org/T112250
In essense, it would be helpful if memento_client raised more exceptions.

**Comment by jayvdb** [comment]
But we should probably close this ticket and create more specific issues for that ;-)

**Comment by shawnmjones** [comment]
I'm glad to hear back from you and, yes, we would appreciate a specific ticket for the error messages.

We created test code to address the requested session issue. It is currently sitting at my fork here:
https://github.com/shawnmjones/py-memento-client/tree/session-management 

I was waiting to hear back before issuing a pull request. :)
